const Translations = {
  // Navigation & Sections
  'Home': 'হোম',
  'Salah Tracker': 'সালাত ট্র্যাকার',
  'Salah': 'সালাত',
  'Dhikr Counter': 'যিকির কাউন্টার',
  'Dhikr': 'যিকির',
  'Nafl Salah': 'নফল সালাত',
  'Nafl': 'নফল',
  'Habits': 'হ্যাবিটস',
  'HABITS': 'হ্যাবিটস',
  'Islamic Finance': 'ফাইন্যান্স',
  'Finance': 'ফাইন্যান্স',
  'Gym': 'জিম',
  'GYM': 'জিম',
  'Career': 'ক্যারিয়ার',
  'CAREER': 'ক্যারিয়ার',
  'Analysis': 'বিশ্লেষণ',
  'Profile': 'প্রোফাইল',
  'Data & Backup': 'ডেটা ও ব্যাকআপ',
  'About': 'সম্পর্কে',
  'Landing': 'ল্যান্ডিং',
  'Manual': 'ব্যবহার নির্দেশিকা',
  'User Manual': 'ব্যবহার নির্দেশিকা',
  'Guide': 'নির্দেশিকা',
  'Settings': 'সেটিংস',
  'Install App': 'অ্যাপ ইনস্টল করুন',

  // Welcome & Setup
  'Welcome': 'স্বাগতম',
  'Skip to main content': 'সরাসরি মূল অংশে যান',
  'Dhikr History': 'যিকিরের ইতিহাস',
  'Saved Profiles on Device': 'ডিভাইসে সংরক্ষিত প্রোফাইলসমূহ',
  'OR CREATE NEW': 'অথবা নতুন তৈরি করুন',
  'What should we call you?': 'আপনাকে কী নামে সম্বোধন করব?',
  "Let's personalize your spiritual companion": 'আপনার দ্বীনি সঙ্গীটিকে আপনার মতো করে সাজিয়ে নিন',
  'Continue →': 'এগিয়ে যান →',
  'Already have a backup? Restore JSON': 'আগের ব্যাকআপ আছে? JSON রিস্টোর করুন',
  'Who are you?': 'আপনি কে?',
  'This personalizes prayer times & greetings': 'এটি সালাতের সময়সূচি ও শুভেচ্ছা বার্তা কাস্টমাইজ করবে',
  'Male': 'পুরুষ',
  'Brother': 'ভাই',
  'Female': 'নারী',
  'Sister': 'বোন',
  'Gender': 'লিঙ্গ',
  '← Back': '← পেছনে',
  'When were you born?': 'আপনার জন্ম কবে?',
  'Scroll to select · Optional': 'স্ক্রল করে নির্বাচন করুন · ঐচ্ছিক',
  'Day': 'দিন',
  'Month': 'মাস',
  'Year': 'বছর',
  'Almost there!': 'প্রায় সম্পন্ন!',
  'Your location calculates exact prayer times': 'আপনার অবস্থান থেকে নিখুঁত সালাতের সময় হিসাব করা হবে',
  'Auto-Detect My Location': 'স্বয়ংক্রিয়ভাবে লোকেশন শনাক্ত করুন',
  'Tap to detect your GPS coordinates': 'জিপিএস কো-অর্ডিনেট শনাক্ত করতে ট্যাপ করুন',
  'Latitude': 'অক্ষাংশ (Lat)',
  'Longitude': 'দ্রাঘিমাংশ (Lng)',
  'Start Journey': 'যাত্রা শুরু করুন',
  'All data is saved locally on your device. No internet required.': 'সমস্ত তথ্য আপনার ডিভাইসেই সংরক্ষিত থাকে। কোনো ইন্টারনেটের প্রয়োজন নেই।',

  // Dashboard & Home
  'Today': 'আজ',
  ' Today': ' আজকে',
  'Habits & Sunnah': 'অভ্যাস ও সুন্নাহ',
  'Knowledge Hub': 'জ্ঞানের হাব',
  'Total Vault Savings': 'মোট ভল্ট সেভিংস',
  'Total Balance': 'মোট ব্যালেন্স',
  'As-salamu alaykum, ': 'আস-সালামু আলাইকুম, ',
  'GOOD MORNING': 'শুভ সকাল',
  'GOOD AFTERNOON': 'শুভ অপরাহ্ন',
  'GOOD EVENING': 'শুভ সন্ধ্যা',
  'GOOD NIGHT': 'শুভ রাত্রি',
  'Good Morning': 'শুভ সকাল',
  'Good Noon': 'শুভ দুপুর',
  'Good Afternoon': 'শুভ অপরাহ্ন',
  'Good Evening': 'শুভ সন্ধ্যা',
  'Good Night': 'শুভ রাত্রি',
  'NEXT PRAYER': 'পরবর্তী সালাত',
  'Next Prayer': 'পরবর্তী সালাত',
  'Remaining': 'বাকি আছে',
  "Today's Salah": 'আজকের সালাত',
  'prayers completed': 'ওয়াক্ত সম্পন্ন',
  'of 5': '৫ এর মধ্যে',
  'Perfect': 'পারফেক্ট',
  'CURRENT RANK': 'বর্তমান র‍্যাঙ্ক',
  'Current Rank': 'বর্তমান পদমর্যাদা',
  'SPIRITUAL INSIGHT': 'আধ্যাত্মিক বার্তা',
  'LIVE WAQT': 'লাইভ ওয়াক্ত',
  'UPCOMING WAQT': 'আসন্ন ওয়াক্ত',
  'SPIRITUAL ENERGY': 'আধ্যাত্মিক শক্তি',
  'ACTIVE STREAKS': 'সক্রিয় স্ট্রিকসমূহ',
  'Dhikr Today': 'আজকের যিকির',
  'Verse of the Day': 'আজকের আয়াত',
  'Monthly Calendar': 'মাসিক ক্যালেন্ডার',
  'Export PDF': 'পিডিএফ এক্সপোর্ট',
  'Daily Performance': 'দৈনিক পারফরম্যান্স',
  'Prayer Schedule': 'সালাত সূচি',
  'Spiritual Energy Meter': 'আধ্যাত্মিক শক্তি মিটার',
  
  // Spiritual Ranks
  'Ghafil': 'জাগ্রত',
  'Awakening': 'জাগ্রত',
  'Musafir': 'আত্মসচেতন',
  'Intentional': 'আত্মসচেতন',
  'Murid': 'ধারাবাহিক',
  'Consistent': 'ধারাবাহিক',
  'Talib': 'অদম্য',
  'Resilient': 'অদম্য',
  'Mindful': 'ফোকাসড',
  'Mukhlis': 'তাকওয়াবান',
  'Muttaqi': 'মুত্তাকী',
  'God-Conscious': 'তাকওয়াবান',
  'Siddiq': 'সিদ্দিক',
  'Muhsin': 'ইহসান',
  'Ihsan': 'ইহসান',
  'NEXT: MUSAFIR': 'পরবর্তী: আত্মসচেতন',
  'NEXT: INTENTIONAL': 'পরবর্তী: আত্মসচেতন',
  'NEXT: MURID': 'পরবর্তী: ধারাবাহিক',
  'NEXT: CONSISTENT': 'পরবর্তী: ধারাবাহিক',
  'NEXT: TALIB': 'পরবর্তী: অদম্য',
  'NEXT: RESILIENT': 'পরবর্তী: অদম্য',
  'NEXT: MINDFUL': 'পরবর্তী: ফোকাসড',
  'NEXT: GOD-CONSCIOUS': 'পরবর্তী: তাকওয়াবান',
  'MAX RANK': 'সর্বোচ্চ র‍্যাঙ্ক (ইহসান)',

  // Salah Module
  'Fajr': 'ফজর',
  'Dhuhr': 'যোহর',
  'Asr': 'আসর',
  'Maghrib': 'মাগরিব',
  'Isha': 'এশা',
  'fajr': 'ফজর',
  'dhuhr': 'যোহর',
  'asr': 'আসর',
  'maghrib': 'মাগরিব',
  'isha': 'এশা',
  'tahajjud': 'তাহাজ্জুদ',
  'jummah': 'জুমআ',
  'Reset Today': 'আজকের ডেটা রিসেট',
  'Prayer Settings': 'সালাত সেটিংস',
  "Jumu'ah": 'জুমআ',
  'Dawn': 'ভোর',
  'Midday': 'দুপুর',
  'Afternoon': 'বিকাল',
  'Sunset': 'সন্ধ্যা',
  'Night': 'রাত',
  'NEXT': 'পরবর্তী',
  'Pending': 'অপেক্ষমান',
  'PENDING': 'অপেক্ষমান',
  'pending': 'অপেক্ষমান',
  'Successful': 'সফল',
  'Unsuccessful': 'অসফল',
  'How did you pray?': 'আপনি কিভাবে সালাত আদায় করেছেন?',
  "Jama'at": 'জামায়াত',
  'Alone': 'একাকী',
  'pts': 'পয়েন্ট',
  'Future Date Locked': 'ভবিষ্যতের তারিখ লক করা',
  'You can only record prayers for today or past dates.': 'আপনি কেবল আজ বা অতীতের সালাত রেকর্ড করতে পারেন।',
  'Congregation': 'জামায়াত',
  'Individual': 'একাকী',
  'Made up later': 'দেরিতে/কাযা',
  'Not prayed': 'আদায় করা হয়নি',
  'Points': 'পয়েন্ট',
  'Score': 'স্কোর',
  'Daily Prayer Record': 'দৈনিক সালাতের বিবরণ',
  'Daily Prayer Log': 'দৈনিক সালাত লগ',
  'Farz Prayers': 'ফরয সালাতসমূহ',
  'Qaza': 'কাযা',
  'Correct': 'সংশোধন',
  'Prayed': 'আদায় করা হয়েছে',
  'Missed': 'মিস হয়েছে',
  'On Time': 'সময়মতো',
  'Late': 'দেরিতে',

  // Nafl & Sunnah Module
  'Nafl Logs': 'নফল লগ',
  '12 Rak\'ah': '১২ রাকাত',
  '12 Rak\'ah + Witr': '১২ রাকাত + বিতর',
  'Night Prayers': 'রাতের সালাত',
  'Tahajjud & Witr': 'তাহাজ্জুদ ও বিতর',
  'Witr & Tahajjud': 'বিতর ও তাহাজ্জুদ',
  'Tahajjud': 'তাহাজ্জুদ',
  'Night Vigils': 'রাতের ইবাদত',
  'Tahajjud Prayed': 'তাহাজ্জুদ আদায় করা হয়েছে',
  'Tahajjud Missed': 'তাহাজ্জুদ মিস হয়েছে',
  'Missed tonight': 'আজ রাতে মিস হয়েছে',
  'Witr': 'বিতর',
  'Wajib': 'ওয়াজিব',
  'Witr Prayed': 'বিতর আদায় করা হয়েছে',
  'Witr Missed': 'বিতর মিস হয়েছে',
  '3 Rakat Wajib': '৩ রাকাত ওয়াজিব',
  'Sunnah': 'সুন্নাহ',
  "Sunnah Mu'akkadah": "সুন্নাহ মুআক্কাদাহ",
  'Sunnah Prayed': 'সুন্নাহ আদায় করা হয়েছে',
  'Sunnah Missed': 'সুন্নাহ মিস হয়েছে',
  'Alhamdulillah': 'আলহামদুলিল্লাহ',
  'Missed today': 'আজ মিস হয়েছে',
  'Select Rakat': 'রাকাত বাছাই করুন',
  'RK': 'রাকাত',
  'Rakat': 'রাকাত',
  'Custom': 'কাস্টম',
  'Dhuhr (B)': 'যোহর (পূর্ব)',
  'Dhuhr (A)': 'যোহর (পর)',

  // Dhikr Module
  'SubhanAllah': 'সুবহানাল্লাহ',
  'Allahu Akbar': 'আল্লাহু আকবার',
  'La ilaha illallah': 'লা ইলাহা ইল্লাল্লাহ',
  'Astaghfirullah': 'আস্তাগফিরুল্লাহ',
  'Target:': 'লক্ষ্য:',
  'Reset': 'রিসেট',
  'Total Count': 'সর্বমোট গণনা',
  'Sessions': 'সেশনসমূহ',
  'Presets': 'প্রিসেট',
  'Tap anywhere to count': 'গণনা করতে যেকোনো স্থানে ট্যাপ করুন',
  'Current Session': 'বর্তমান সেশন',
  'Session History': 'সেশনের ইতিহাস',
  'Add Custom Dhikr': 'নতুন যিকির যোগ করুন',

  // Habits & Iron Will Module
  'The Forge of Resolve': 'সংকল্পের কামারশালা',
  'Initiate First Habit': 'প্রথম অভ্যাস শুরু করুন',
  'Active Wars': 'সক্রিয় যুদ্ধ',
  'Badges Earned': 'অর্জিত ব্যাজ',
  'Days': 'দিন',
  'Hours': 'ঘণ্টা',
  'Minutes': 'মিনিট',
  'Seconds': 'সেকেন্ড',
  'History': 'ইতিহাস',
  'Clean': 'পবিত্র',
  'Relapse': 'পতন',
  'Start Date': 'শুরুর তারিখ',
  'Years': 'বছর',
  'Active': 'সক্রিয়',
  'Completed': 'সম্পন্ন',
  'Archived': 'আর্কাইভড',
  'New Goal': 'নতুন লক্ষ্য',
  'New Habit': 'নতুন অভ্যাস',
  'Cancel': 'বাতিল',
  'Save Goal': 'সেভ করুন',
  'Save Habit': 'অভ্যাস সেভ করুন',
  'Title': 'শিরোনাম',
  'Description': 'বিবরণ',
  'Target': 'লক্ষ্যমাত্রা',
  'Unit': 'একক',
  'Category': 'বিভাগ',
  'Priority': 'অগ্রাধিকার',
  'Deadline': 'শেষ সময়',
  'Recurring': 'পুনরাবৃত্তি',
  'WARRIOR SPIRIT POWER': 'হ্যাবিট রেজিলিয়েন্স পাওয়ার',
  'HABIT RESILIENCE POWER': 'হ্যাবিট রেজিলিয়েন্স পাওয়ার',
  'Total Combined Days of Purity': 'পবিত্রতার মোট দিন',
  'Add Another Habit to Conquer': 'জয়ের জন্য নতুন অভ্যাস যোগ করুন',
  'Your Badges': 'আপনার ব্যাজসমূহ',
  'Your Badges & Ranks': 'আপনার ব্যাজ ও পদমর্যাদা',
  'Emergency Panic Button': 'জরুরি প্যানিক বাটন',
  'Breathing Exercise': 'শ্বাস-প্রশ্বাসের ব্যায়াম',
  'Relapse Emergency Protocol': 'পতন রোধে জরুরি পদক্ষেপ',
  'Reset All Timers': 'সব টাইমার রিসেট',
  'Clear All Data': 'সব ডেটা মুছুন',
  'Clean Day': 'পবিত্র দিন',
  'Undo Relapse': 'পতন বাতিল করুন',
  'Log Relapse': 'পতন রেকর্ড করুন',
  'Trigger / Note': 'কারণ বা নোট',
  'Purity Milestones': 'পবিত্রতার মাইলফলক',
  'Find your center': 'নিজেকে শান্ত ও কেন্দ্রীভূত করুন',
  'Ready?': 'প্রস্তুত?',
  'Inhale': 'শ্বাস নিন',
  'Hold': 'ধরে রাখুন',
  'Exhale': 'শ্বাস ছাড়ুন',
  'Session Complete': 'সেশন সম্পন্ন',
  'Take a moment. You are present.': 'এক মুহূর্ত স্থির থাকুন। আপনি বিজয়ী।',
  'Repeat Round': 'পুনরায় করুন',

  // Gym & Nutrition Module
  'Gym & Diet': 'জিম ও ডায়েট',
  'Gym Tracker': 'জিম ট্র্যাকার',
  'Gym & Nutrition': 'জিম ও পুষ্টি',
  'Training & Recovery': 'ট্রেনিং ও রিকভারি',
  'PERFORMANCE OS': 'পারফরম্যান্স ওএস',
  'Train with focus.': 'মনোযোগের সাথে অনুশীলন করুন।',
  'Recover with intention.': 'পরিকল্পিতভাবে বিশ্রাম নিন।',
  'Track every session, keep nutrition aligned, and turn your routine into a clearer, more disciplined system.': 'প্রতিটি সেশন ট্র্যাক করুন, সঠিক পুষ্টি বজায় রাখুন এবং জীবনযাত্রাকে সুশৃঙ্খল সিস্টেমে রূপান্তর করুন।',
  'Log Workout & Diet': 'ওয়ার্কআউট ও ডায়েট যোগ করুন',
  'Log Workout': 'ওয়ার্কআউট যোগ করুন',
  'Log Sleep': 'ঘুম রেকর্ড করুন',
  'Log Hydration': 'পানি পান রেকর্ড করুন',
  'Workout Logger': 'ওয়ার্কআউট লগার',
  'Workout Split': 'ওয়ার্কআউট স্প্লিট',
  'Exercises': 'অনুশীলনসমূহ',
  'Add Exercise': 'অনুশীলন যোগ করুন',
  'Exercise Name': 'অনুশীলনের নাম',
  'Sets': 'সেট',
  'Reps': 'রেপস',
  'Weight': 'ওজন',
  'Weight (kg)': 'ওজন (কেজি)',
  'Body Fat (%)': 'বডি ফ্যাট (%)',
  'Body Metrics': 'শারীরিক মেট্রিক্স',
  'Nutrition': 'পুষ্টি',
  'Diet & Nutrition': 'ডায়েট ও পুষ্টি',
  'Sleep & Recovery': 'ঘুম ও রিকভারি',
  'Bedtime': 'ঘুমানোর সময়',
  'Wake Up': 'ঘুম থেকে ওঠার সময়',
  'Sleep Quality': 'ঘুমের মান',
  'Restless': 'অস্থির',
  'Light Sleep': 'হালকা ঘুম',
  'Deep': 'গভীর ঘুম',
  'Weekly': 'সাপ্তাহিক',
  'Monthly': 'মাসিক',
  'Yearly': 'বাৎসরিক',
  'Progress': 'অগ্রগতি',
  'Currency': 'কারেন্সি / মুদ্রা',
  'Detect Location': 'লোকেশন শনাক্ত করুন',
  'Awakening': 'জাগ্রত',
  'Seeker': 'সন্ধানী',
  'Devoted': 'নিবেদিতপ্রাণ',
  'Guardian': 'অভিভাবক',
  'Ascendant': 'উন্নত',
  'Luminous': 'উজ্জ্বল',
  'Transcendent': 'মহিমান্বিত',
  'Release notes & build info': 'রিলিজ নোট ও বিল্ড তথ্য',
  'Add a new goal...': 'নতুন লক্ষ্য যোগ করুন...',
  'Exercise name — e.g. Bench Press, Squat...': 'অনুশীলনের নাম — যেমন বেঞ্চ প্রেস, স্কোয়াট...',
  'Recovery': 'রিকভারি',
  'Hydration': 'পানি পান',
  'Water Tracker': 'পানি ট্র্যাকার',
  'Total Water Intake': 'মোট পানি গ্রহণ',
  'Target Hydration': 'টার্গেট পানি গ্রহণ',
  'Daily Goal': 'দৈনিক লক্ষ্য',
  'of 3000 ml': '৩০০০ মিলির মধ্যে',
  '100 ml': '১০০ মিলি',
  '250 ml': '২৫০ মিলি',
  '500 ml': '৫০০ মিলি',
  '-250 ml': '-২৫০ মিলি',
  'Total Calories': 'মোট ক্যালরি',
  'Protein': 'প্রোটিন',
  'Carbs': 'কার্বস',
  'Fats': 'ফ্যাট',
  'Add Meal': 'খাবার যোগ করুন',
  'Meal type': 'খাবারের ধরন',
  'breakfast': 'সকালের খাবার',
  'lunch': 'দুপুরের খাবার',
  'dinner': 'রাতের খাবার',
  'snack': 'স্ন্যাক্স',
  'Breakfast': 'সকালের খাবার',
  'Lunch': 'দুপুরের খাবার',
  'Dinner': 'রাতের খাবার',
  'Snack': 'স্ন্যাক্স',
  'Push': 'পুশ',
  'Pull': 'পুল',
  'Legs': 'লেগস',
  'Upper': 'আপার বডি',
  'Lower': 'লোয়ার বডি',
  'Rest Day': 'বিশ্রামের দিন',
  'Full Body': 'ফুল বডি',
  'Custom Split': 'কাস্টম স্প্লিট',
  'No exercises logged today': 'আজ কোনো অনুশীলন রেকর্ড করা হয়নি',
  'No exercises logged yet': 'এখনো কোনো অনুশীলন রেকর্ড করা হয়নি',
  'PR': 'ব্যক্তিগত রেকর্ড',
  'Personal Records': 'ব্যক্তিগত রেকর্ডসমূহ',
  'Optimal': 'অনুকূল',
  'OPTIMAL': 'অনুকূল',
  'Deficit': 'ঘাটতি',
  'DEFICIT': 'ঘাটতি',
  'Surplus': 'উদ্বৃত্ত',
  'SURPLUS': 'উদ্বৃত্ত',
  'LOGGED': 'রেকর্ডকৃত',
  'Logged': 'লগ করা হয়েছে',
  'Readiness': 'প্রস্তুতি',
  'Volume': 'ভলিউম',
  'kg lifted': 'কেজি উত্তোলন',
  'done today': 'আজ সম্পন্ন',
  'Bench Press': 'বেঞ্চ প্রেস',
  'Overhead Press': 'ওভারহেড প্রেস',
  'Incline Dumbbell Press': 'ইনক্লাইন ডাম্বেল প্রেস',
  'Tricep Pushdown': 'ট্রাইসেপ পুশডাউন',
  'Pull-ups': 'পুল-আপস',
  'Barbell Row': 'বারবেল রো',
  'Face Pulls': 'ফেস পুলস',
  'Bicep Curls': 'বাইসেপ কার্লস',
  'Squat': 'স্কোয়াট',
  'Romanian Deadlift': 'রোমানিয়ান ডেডলিফট',
  'Leg Press': 'লেগ প্রেস',
  'Calf Raises': 'কাফ রেইজেস',
  'Deadlift': 'ডেডলিফট',
  'Hip Thrust': 'হিপ থ্রাস্ট',

  // Career & Deep Work Module
  'Career Builder': 'ক্যারিয়ার বিল্ডার',
  'CAREER OS': 'ক্যারিয়ার ওএস',
  'Build with discipline.': 'শৃঙ্খলার সাথে গড়ে তুলুন।',
  'Execute with purpose.': 'লক্ষ্যের সাথে বাস্তবায়ন করুন।',
  'Log study sessions, track core skill developments, hit your checklist goals, and turn daily small victories into your absolute professional edge.': 'পড়াশোনার সেশন রেকর্ড করুন, দক্ষতা বৃদ্ধি ট্র্যাক করুন এবং প্রতিদিনের ছোট ছোট জয়কে অনন্য সাফল্যে রূপান্তর করুন।',
  'A focused workspace for your most important goals. Tap a task to complete it, or use smart suggestions to move faster.': 'আপনার গুরুত্বপূর্ণ লক্ষ্য অর্জনের একটি ফোকাসড ওয়ার্কস্পেস। যেকোনো টাস্ক সম্পন্ন করতে ট্যাপ করুন।',
  'Study & Deep Work': 'অধ্যয়ন ও ডিপ ওয়ার্ক',
  'Focus Timer': 'ফোকাস টাইমার',
  'Study Log': 'অধ্যয়ন লগ',
  'Daily Goals': 'দৈনিক লক্ষ্যসমূহ',
  'Daily Goals Log': 'দৈনিক লক্ষ্য লগ',
  'Focus Topic': 'ফোকাসের বিষয়',
  'Duration': 'সময়কাল',
  'Notes': 'নোট / বিবরণ',
  'Start': 'শুরু',
  'Stop': 'বন্ধ',
  'Pause': 'বিরতি',
  'Log': 'লগ করুন',
  'Coding': 'কোডিং',
  'Reading': 'অধ্যয়ন/পড়া',
  'Language': 'ভাষা শিক্ষা',
  'Business': 'ব্যবসা/বাণিজ্য',
  'Research': 'গবেষণা',
  'Design': 'ডিজাইন',
  'Writing': 'লেখালেখি',
  'General': 'সাধারণ',
  'Expert': 'বিশেষজ্ঞ',
  'Specialist': 'বিশেষজ্ঞ',
  'Practitioner': 'অনুশীলনকারী',
  'Novice': 'নবীশ',
  'Master': 'মাস্টার',
  'Grandmaster': 'গ্র্যান্ডমাস্টার',
  'Day Streak': 'দিনের স্ট্রিক',
  'By Category': 'বিভাগ অনুযায়ী',
  '14-Day Study Trend': '১৪-দিনের অধ্যয়ন প্রবণতা',
  'Study Hours This Week': 'এই সপ্তাহের অধ্যয়ন ঘণ্টা',
  'Last 7 days': 'শেষ ৭ দিন',
  'hours this mo.': 'ঘণ্টা এই মাসে',
  'Deep Work Hours': 'ডিপ ওয়ার্ক ঘণ্টা',
  'Productivity Score': 'উৎপাদনশীলতা স্কোর',
  'Add Checklist Item': 'নতুন টাস্ক যোগ করুন',
  'Quick Add Goals': 'দ্রুত লক্ষ্য যোগ',
  'Write Daily Journal': 'দৈনিক ডায়েরি লিখুন',
  'Review Weekly Roadmap': 'সাপ্তাহিক রোডম্যাপ পর্যালোচনা',
  'Solve 1 Complex Problem': '১টি জটিল সমস্যা সমাধান',

  // Spiritual Health Analysis Module
  'Spiritual Health Analysis': 'আধ্যাত্মিক স্বাস্থ্য বিশ্লেষণ',
  'Spiritual Balance': 'আধ্যাত্মিক ভারসাম্য',
  'Progress Timeline': 'অগ্রগতির টাইমলাইন',
  'Insight Breakdown': 'বিশদ বিবরণ',
  'Lamim Spirituality': 'লামিম আধ্যাত্মিকতা',
  'Total LSS': 'মোট LSS স্কোর',
  'PDF Report': 'পিডিএফ রিপোর্ট',
  'Spirit': 'স্পিরিট',
  'Spirit Power': 'স্পিরিট পাওয়ার',
  'Consistency Rate': 'ধারাবাহিকতার হার',
  'Prayer Discipline': 'সালাতের শৃঙ্খলা',
  'Habit Mastery': 'অভ্যাসের ওপর নিয়ন্ত্রণ',
  'Charity & Wealth': 'দান ও হালাল সম্পদ',
  'Focus & Mindfulness': 'মনোযোগ ও একাগ্রতা',
  '30-Day Trend': '৩০ দিনের প্রবণতা',
  'Streak Analysis': 'স্ট্রিক বিশ্লেষণ',
  'Current Streak': 'বর্তমান স্ট্রিক',
  'Longest Streak': 'সর্বোচ্চ স্ট্রিক',
  'Peak Performance Day': 'শীর্ষ পারফরম্যান্সের দিন',
  'Daily Average Score': 'দৈনিক গড় স্কোর',
  'Farz Salah Consistency': 'ফরয সালাতের ধারাবাহিকতা',
  'Sunnah & Nafl Prayers': 'সুন্নাহ ও নফল সালাত',
  'Dhikr Engagement': 'যিকিরে সম্পৃক্ততা',
  'Iron Will Purity': 'দৃঢ় সংকল্প ও পবিত্রতা',
  'Halal Financial Health': 'হালাল আর্থিক স্বাস্থ্য',
  'This Month': 'এই মাস',
  'Weekly Performance': 'সাপ্তাহিক পারফরম্যান্স',
  'Monthly Comparison': 'মাসিক তুলনা',

  // Islamic Finance Module
  'Add Income': 'আয় যোগ করুন',
  'Add Expense': 'ব্যয় যোগ করুন',
  'Transaction History': 'লেনদেনের ইতিহাস',
  'Vaults': 'ভল্টসমূহ',
  'Vaults & Savings Goals': 'ভল্ট ও সঞ্চয় লক্ষ্য',
  'Amount': 'পরিমাণ',
  'Spending Analysis': 'ব্যয় বিশ্লেষণ',
  'Daily breakdown of this month': 'এই মাসের দৈনিক হিসাব',
  'DAILY': 'দৈনিক',
  'MONTHLY': 'মাসিক',
  'Deposit': 'জমা',
  'Spend': 'ব্যয়',
  'Transfer': 'স্থানান্তর',
  'No recent transactions': 'সাম্প্রতিক কোনো লেনদেন নেই',
  'Net Worth': 'মোট সম্পদ',
  'Total Income': 'মোট আয়',
  'Total Expense': 'মোট ব্যয়',
  'Vault Savings': 'ভল্ট সেভিংস',
  'Monthly Budget': 'মাসিক বাজেট',
  'Payment Method': 'পেমেন্ট মাধ্যম',
  'Cash': 'নগদ ক্যাশ',
  'Bank': 'ব্যাংক একাউন্ট',
  'Mobile Wallet': 'মোবাইল ওয়ালেট (বিকাশ/নগদ)',
  'Card': 'কার্ড',
  'Search categories...': 'ক্যাটাগরি খুঁজুন...',
  'Search transactions...': 'লেনদেন খুঁজুন...',
  'Search vaults...': 'ভল্ট খুঁজুন...',
  'Search habits...': 'হ্যাবিট খুঁজুন...',
  'Salary, Freelance, Gift etc.': 'যেমন: বেতন, ফ্রিল্যান্সিং, উপহার ইত্যাদি',
  'e.g. Dream House, iPhone 16, Hajj Fund': 'যেমন: স্বপ্নের বাড়ি, নতুন ফোন, হজ্জ ফান্ড',
  'e.g. Rice, Lentils, Fish & Salad': 'যেমন: ভাত, ডাল, মাছ ও সালাদ',
  'Note / Memo': 'নোট / বিবরণ',
  'Save Transaction': 'লেনদেন সেভ করুন',
  'Create New Vault': 'নতুন ভল্ট খুলুন',
  'Vault Name': 'ভল্টের নাম',
  'Target Amount': 'লক্ষ্যমাত্রা (টাকা)',
  'Saved Amount': 'জমা হওয়া টাকা',
  'Deposit to Vault': 'ভল্টে জমা দিন',
  'Withdraw from Vault': 'ভল্ট থেকে উত্তোলন',
  'Zakat Calculator': 'যাকাত ক্যালকুলেটর',
  'Nisab Threshold': 'নিসাব পরিমাণ',
  'Zakat Eligible Assets': 'যাকাতযোগ্য সম্পদ',
  'Total Zakat Due': 'প্রদেয় মোট যাকাত',
  'Calculate Zakat': 'যাকাত হিসাব করুন',
  'Halal Wealth': 'হালাল সম্পদ',

  // Profile & Settings Module
  'Personal Information': 'ব্যক্তিগত তথ্য',
  'App Settings': 'অ্যাপ সেটিংস',
  'App Appearance': 'অ্যাপের দৃশ্যরূপ',
  'Danger Zone': 'বিপজ্জনক জোন',
  'Theme': 'থিম',
  'Dark': 'ডার্ক মোড',
  'Light': 'লাইট মোড',
  'System Default': 'সিস্টেম ডিফল্ট',
  'Export Backup JSON': 'ব্যাকআপ ফাইল এক্সপোর্ট',
  'Restore Backup JSON': 'ব্যাকআপ ফাইল রিস্টোর',
  'Save backup file to device': 'ডিভাইসে ব্যাকআপ সেভ করুন',
  'Import saved backup file': 'সেভ করা ব্যাকআপ ফাইল ইমপোর্ট করুন',
  'Export Data': 'ডেটা এক্সপোর্ট',
  'Import Data': 'ডেটা ইমপোর্ট',
  'JSON Backup': 'JSON ব্যাকআপ',
  'Export Salah Log': 'সালাত লগ এক্সপোর্ট',
  'Logout': 'লগ আউট',
  'Log Out (Keep Data)': 'লগ আউট (ডাটা থাকবে)',
  'Delete Account': 'অ্যাকাউন্ট মুছুন',
  'Delete Account & All Data': 'অ্যাকাউন্ট ও সব ডাটা মুছুন',
  'Delete Active Profile & Data': 'বর্তমান প্রোফাইল ও ডাটা মুছুন',
  'Factory Reset App': 'ফ্যাক্টরি রিসেট',
  'Factory Reset Sub': 'অ্যাপ, ডাটা ও ক্যাশে মুছে ফেলে',
  'Erase app, data & cache': 'অ্যাপ, ডাটা ও ক্যাশে মুছে ফেলে',
  'Erase app, data &amp; cache': 'অ্যাপ, ডাটা ও ক্যাশে মুছে ফেলে',
  'App Version': 'অ্যাপ ভার্সন',
  'Privacy Policy': 'প্রাইভেসি পলিসি',
  'Prayer Notifications': 'সালাতের নোটিফিকেশন',
  'Calc Method': 'হিসাব পদ্ধতি',
  'Madhab': 'মাযহাব',
  'Name': 'নাম',
  'Email': 'ইমেইল',
  'Location': 'অবস্থান',
  'Not set': 'সেট করা নেই',
  'Bio / Status': 'বায়ো / স্ট্যাটাস',
  'Date of Birth': 'জন্মতারিখ',
  'Jumu\'ah Mode': 'জুমআ মোড',
  'Show Jumu\'ah on Fridays': 'শুক্রবারে জুমআ প্রদর্শন করুন',
  'Alerts for next waqt': 'পরবর্তী ওয়াক্তের অ্যালার্ট',
  'Language / ভাষা': 'Language / ভাষা',
  'Bangla': 'বাংলা',
  'English': 'English',
  'Profile Switcher': 'প্রোফাইল সুইচ করুন',
  'Active Profile': 'বর্তমান সক্রিয় প্রোফাইল',
  'Switch Profile': 'প্রোফাইল পরিবর্তন',
  'Create New Profile': 'নতুন প্রোফাইল তৈরি করুন',
  'Delete Profile': 'প্রোফাইল মুছুন',
  'Yearly': 'বাৎসরিক',
  'Value': 'মান',
  'Spirituality Companion': 'দ্বীনি ও জীবন সঙ্গী',
  'Stable': 'স্ট্যাবল',
  'Released': 'রিলিজকৃত',
  'Channel': 'চ্যানেল',
  'Platform': 'প্ল্যাটফর্ম',
  'Offline PWA': 'অফলাইন PWA',
  'Architecture': 'আর্কিটেকচার',
  'Vanilla JS': 'ভ্যানিলা জেএস',
  'What\'s New': 'নতুন কী আছে',
  'This Device': 'এই ডিভাইস',

  // Units & Time
  'day': 'দিন',
  'days': 'দিন',
  'hours': 'ঘণ্টা',
  'hour': 'ঘণ্টা',
  'hrs': 'ঘণ্টা',
  'minutes': 'মিনিট',
  'mins': 'মিনিট',
  'min': 'মিনিট',
  'sec': 'সেকেন্ড',
  'ml': 'মিলি',
  'kg': 'কেজি',
  '11:00 PM': '১১:০০ রাত',
  '07:00 AM': '০৭:০০ সকাল',
  '6 PM': 'সন্ধ্যা ৬টা',
  '9 PM': 'রাত ৯টা',
  '12 AM': 'রাত ১২টা',
  '3 AM': 'রাত ৩টা',
  '6 AM': 'সকাল ৬টা',
  '4 AM': 'ভোর ৪টা',
  '7 AM': 'সকাল ৭টা',
  '10 AM': 'সকাল ১০টা',
  '1 PM': 'দুপুর ১টা',
  '4 PM': 'বিকাল ৪টা',

  // Global Dialogs & Actions
  'Save': 'সেভ করুন',
  'Delete': 'মুছুন',
  'Edit': 'এডিট',
  'Confirm': 'নিশ্চিত করুন',
  'Success': 'সফল',
  'Error': 'ত্রুটি',
  'All 5': 'সবগুলো',
  'None': 'একটিও না',
  'Next': 'পরবর্তী',
  'Previous': 'পূর্ববর্তী',
  'Close': 'বন্ধ',
  'Loading...': 'লোড হচ্ছে...',
  'Retry': 'পুনরায় চেষ্টা',
  'No data': 'কোনো ডেটা নেই',
  'Updated': 'আপডেট হয়েছে',
  'Copied': 'কপি হয়েছে',
  'Share': 'শেয়ার',
  'Download': 'ডাউনলোড',
  'Add': 'যোগ করুন',
  'Remove': 'মুছে ফেলুন',
  'Done': 'সম্পন্ন',
  'Yes, Clear All': 'হ্যাঁ, মুছে ফেলুন',
  'Reset Data?': 'ডেটা রিসেট করবেন?',
  'Are you sure you want to clear all data for this section today?': 'আপনি কি নিশ্চিত যে এই সেকশনের আজকের সমস্ত তথ্য মুছে ফেলতে চান?',

  // Toasts
  'Great job! Stay strong! ': 'অসাধারণ! শক্ত থাকুন! ',
  'Day marked as clean! Keep going! ': 'দিনটি পরিষ্কার হিসেবে চিহ্নিত! চালিয়ে যান! ',
  'Relapse Undone! Your streak is restored. ️': 'পতন বাতিল করা হয়েছে! আপনার স্ট্রিক ফিরে এসেছে। ️',
  'Habit forged! Your journey begins ️': 'অভ্যাস তৈরি হয়েছে! আপনার যাত্রা শুরু ️',
  'Please select or type a habit name': 'অনুগ্রহ করে একটি অভ্যাসের নাম নির্বাচন করুন বা লিখুন',
  'Start date updated!': 'শুরুর তারিখ আপডেট হয়েছে!',
  'No messages found': 'কোনো বার্তা পাওয়া যায়নি',
  'Location services not supported': 'লোকেশন সার্ভিস সমর্থিত নয়',
  'Detecting your location...': 'আপনার লোকেশন শনাক্ত করা হচ্ছে...',
  'Notifications enabled ': 'নোটিফিকেশন চালু হয়েছে ',
  'This field cannot be empty': 'এই ঘরটি খালি রাখা যাবে না',
  'Salah data cleared': 'সালাতের ডেটা মুছে ফেলা হয়েছে',
  ' MashaAllah! All 5 farz prayers logged!': ' মাশাআল্লাহ! ৫ ওয়াক্ত ফরজ সালাতই রেকর্ড করা হয়েছে!',
  'Copied to clipboard': 'ক্লিপবোর্ডে কপি হয়েছে',
  'Saving...': 'সেভ হচ্ছে...'
};

window.t = function(key) {
  const lang = localStorage.getItem('lamim_lang') || 'en';
  if (lang === 'bn' && Translations[key]) {
    return Translations[key];
  }
  return key;
};

// Translate numbers to Bengali numerals
window.n = function(num) {
  const lang = localStorage.getItem('lamim_lang') || 'en';
  if (lang !== 'bn') return num;
  const bnNums = ['০','১','২','৩','৪','৫','৬','৭','৮','৯'];
  return String(num).replace(/\d/g, d => bnNums[d]);
};
// Auto-Translator MutationObserver
let _translatePending = false;
let _translateMutations = [];
const autoTranslateObserver = new MutationObserver((mutations) => {
  // Accumulate and coalesce bursts into a single per-frame pass so we don't
  // re-walk the entire document on every render / characterData change.
  for (let i = 0; i < mutations.length; i++) _translateMutations.push(mutations[i]);
  autoTranslateObserver.disconnect();

  if (!_translatePending) {
    _translatePending = true;
    const run = () => {
      _translatePending = false;
      const batch = _translateMutations;
      _translateMutations = [];

      const isBn = (localStorage.getItem('lamim_lang') || 'en') === 'bn';
      const bnNums = ['০','১','২','৩','৪','৫','৬','৭','৮','৯'];
      const enNums = {'০':'0','১':'1','২':'2','৩':'3','৪':'4','৫':'5','৬':'6','৭':'7','৮':'8','৯':'9'};

      function processTextNode(node) {
        const p = node.parentElement;
        if (!p) return;
        // Skip script, style, SVG internals, inputs, textareas, and code blocks
        const tag = p.tagName;
        if (tag === 'SCRIPT' || tag === 'STYLE' || tag === 'INPUT' || tag === 'TEXTAREA' || tag === 'CODE' || tag === 'PRE') return;
        if (p.closest('svg')) return; // Never touch SVG content - breaks viewBox, coordinates, etc.
        if (p.closest('[data-no-translate], [contenteditable="true"], .notranslate')) return; // Allow opting out
        let text = node.nodeValue;
        if (!text || !text.trim()) return;

        let changed = false;

        // 1. Text Translation
        let trimmed = text.trim();
        if (isBn && Translations[trimmed]) {
          text = text.replace(trimmed, Translations[trimmed]);
          changed = true;
        }

        // 2. Number Translation
        if (isBn && /\d/.test(text)) {
          text = text.replace(/\d/g, d => bnNums[d]);
          changed = true;
        } else if (!isBn && /[০-৯]/.test(text)) {
          text = text.replace(/[০-৯]/g, d => enNums[d]);
          changed = true;
        }

        if (changed && node.nodeValue !== text) {
          node.nodeValue = text;
        }
      }

      for (let m of batch) {
        if (m.type === 'characterData') {
          processTextNode(m.target);
        } else if (m.type === 'childList') {
          m.addedNodes.forEach(node => {
            if (node.nodeType === Node.TEXT_NODE) {
              processTextNode(node);
            } else if (node.nodeType === Node.ELEMENT_NODE) {
              if (node.tagName === 'SCRIPT' || node.tagName === 'STYLE') return;
              const walk = document.createTreeWalker(node, NodeFilter.SHOW_TEXT, null, false);
              let n;
              while (n = walk.nextNode()) {
                processTextNode(n);
              }
            }
          });
        }
      }

      autoTranslateObserver.observe(document.body, { childList: true, subtree: true, characterData: true });
    };
    if (typeof requestAnimationFrame === 'function') requestAnimationFrame(run);
    else run();
  } else {
    autoTranslateObserver.observe(document.body, { childList: true, subtree: true, characterData: true });
  }
});

// Start observer as soon as possible
if (document.body) {
  autoTranslateObserver.observe(document.body, { childList: true, subtree: true, characterData: true });
}


